name: proyecto_tsp_dev
description: Un recetario que te ayuda en tu dia a dia.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.0.5

  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recetas/ensalada.png
    - assets/recetas/spaghetti.png
    - assets/recetas/huarache.png
    - assets/Recetario.sqlite3
    - assets/recetas/Quesadilla_Atun.png
    - assets/recetas/Lentejas.png
    - assets/recetas/Tortilla_Patatas.png
    - assets/recetas/Sopa_Azteca.png
    - assets/recetas/Pescado_Veracruzana.png
    - assets/recetas/Huevos_Vegetales.png
    - assets/recetas/Ensalada_Nopales.png
    - assets/recetas/Caldo_Verduras.png
    - assets/recetas/Tacos_Pescado.png
    - assets/recetas/Arroz_Verduras.png
    - assets/recetas/Ensalada_Pollo_Ag.png
    - assets/recetas/Tortitas_Calabacita.png
    - assets/recetas/Pescado_Aluminio.png
    - assets/recetas/Chiles_Quinoa.png
    - assets/recetas/Fajitas_Pollo.png
    - assets/recetas/Tostadas_Ag_Frij.png
    - assets/recetas/Ensalada_Espinacas.png