name: proyecto_tsp_dev
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.0.5

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recetas/ensalada.png
    - assets/recetas/spaghetti.png
    - assets/recetas/huarache.png
    - assets/Recetario.sqlite3
  