name: proyecto_tsp_dev
description: Un recetario que te ayuda en tu dia a dia.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.0.5

  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/paper_texture.jpg
    - assets/recetas/ensalada.png
    - assets/recetas/spaghetti.png
    - assets/recetas/huarache.png
    - assets/Recetario.sqlite3
    - assets/recetas/Quesadilla_Atun.png
    - assets/recetas/Lentejas.png
    - assets/recetas/Tortilla_Patatas.png
    - assets/recetas/Sopa_Azteca.png
    - assets/recetas/Pescado_Veracruzana.png
    - assets/recetas/Huevos_Vegetales.png
    - assets/recetas/Ensalada_Nopales.png
    - assets/recetas/Caldo_Verduras.png
    - assets/recetas/Tacos_Pescado.png
    - assets/recetas/Arroz_Verduras.png
    - assets/recetas/Ensalada_Pollo_Ag.png
    - assets/recetas/Tortitas_Calabacita.png
    - assets/recetas/Pescado_Aluminio.png
    - assets/recetas/Chiles_Quinoa.png
    - assets/recetas/Fajitas_Pollo.png
    - assets/recetas/Tostadas_Ag_Frij.png
    - assets/recetas/Ensalada_Espinacas.png
    - assets/recetas/Chilaquiles_Verdes.png
    - assets/recetas/Calabacitas_Mexicana.png
    - assets/recetas/Ensalada_Ga_Pe.png
    - assets/recetas/Sopa_Verduras.png
    - assets/recetas/Bowl_Quinoa.png
    - assets/recetas/Tacos_Lechuga_Pollo.png
    - assets/recetas/Huevos_Mexicana.png
    - assets/recetas/Brochetas_Verduras_Tofu.png
    - assets/recetas/Rollos_Pavo.png
    - assets/recetas/Camarones_Ajillo.png
    - assets/recetas/Alambre_Res.png
    - assets/recetas/Rajas_Poblanas.png
    - assets/recetas/Verdolagas_Carne.png
    - assets/recetas/Espagueti_Horno.png
    - assets/recetas/Carne_Almendra.png
    - assets/recetas/Chiles_Morrones.png
    - assets/recetas/Caldo_Durango.png
    - assets/recetas/Costillas_Cerdo.png
    - assets/recetas/Salmon_Salva.png
    - assets/recetas/Tepache.png
    - assets/recetas/Huevos_Pobres.png
    - assets/recetas/Frijoles_Refritos.png
    - assets/recetas/Sopa_Nopal.png
    - assets/recetas/Croquetas_Jamon.png
    - assets/recetas/Cochinita_Pibil.png
    - assets/recetas/Costillas_Puerco.png
    - assets/recetas/Salteado_Verduras.png
    - assets/ingredientes/lechuga.jpg
    - assets/ingredientes/Aceitunas.jpg
    - assets/ingredientes/Achiote.jpg
    - assets/ingredientes/Aguacate.jpg
    - assets/ingredientes/Almendras.jpg
    - assets/ingredientes/Anis.jpg
    - assets/ingredientes/Apio.jpg
    - assets/ingredientes/Arandano.jpg
    - assets/ingredientes/Arroz.jpg
    - assets/ingredientes/Bistec.jpg
    - assets/ingredientes/Brocoli.jpg
    - assets/ingredientes/Calabaza.jpg
    - assets/ingredientes/Camarones.jpg
    - assets/ingredientes/Canela.jpg
    - assets/ingredientes/Canela_Polvo.jpg
    - assets/ingredientes/Carne_Puerco.jpg
    - assets/ingredientes/Carne_Res.jpg
    - assets/ingredientes/cebolla.jpg
    - assets/ingredientes/Cebolla_Morada.jpg
    - assets/ingredientes/cebollin.jpg
    - assets/ingredientes/Champinones.jpg
    - assets/ingredientes/Chicharos.jpg
    - assets/ingredientes/Chile_Guajillo.jpg
    - assets/ingredientes/Jalapeno.jpg
    - assets/ingredientes/Chile_Morron.jpg
    - assets/ingredientes/Chile_Piquin.jpg
    - assets/ingredientes/Chile_Poblano.jpg
    - assets/ingredientes/Chile_Serrano.jpg
    - assets/ingredientes/Chorizo.jpg
    - assets/ingredientes/Consome_Pollo.jpg
    - assets/ingredientes/Costillas_Puerco.jpg
    - assets/ingredientes/Crema.jpg
    - assets/ingredientes/Crema.jpg
    - assets/ingredientes/dienteajo.jpg
    - assets/ingredientes/Elotes.jpg
    - assets/ingredientes/Espaguetti.jpg
    - assets/ingredientes/Espinaca.jpg
    - assets/ingredientes/Espinaca_Baby.jpg
    - assets/ingredientes/Esparragos.jpg
    - assets/ingredientes/Anchoa.jpg
    - assets/ingredientes/Filete_pescado.jpg
    - assets/ingredientes/Frijoles.jpg
    - assets/ingredientes/Frijoles_Refritos.jpg
    - assets/ingredientes/Garbanzos.jpg
    - assets/ingredientes/Harina.jpg
    - assets/ingredientes/Huevo.jpg
    - assets/ingredientes/jamon.jpg
    - assets/ingredientes/jitomates.jpg
    - assets/ingredientes/Jugo_Naranja.jpg
    - assets/ingredientes/Atun.jpg
    - assets/ingredientes/Leche.jpg
    - assets/ingredientes/Lentejas.jpg
    - assets/ingredientes/Limon.jpg
    - assets/ingredientes/Longaniza.jpg
    - assets/ingredientes/Mantequilla.jpg
    - assets/ingredientes/Masa_Maiz.jpg
    - assets/ingredientes/Naranja.jpg
    - assets/ingredientes/Nopal.jpg
    - assets/ingredientes/Pan.jpg
    - assets/ingredientes/Pan_Molido.jpg
    - assets/ingredientes/Papa.jpg
    - assets/ingredientes/Pechuga_Pavo.jpg
    - assets/ingredientes/Pechuga_Pollo.jpg
    - assets/ingredientes/Pepino.jpg
    - assets/ingredientes/Pierna_Cerdo.jpg
    - assets/ingredientes/Piloncillo.jpg
    - assets/ingredientes/Pina.jpg
    - assets/ingredientes/Puerro.jpg
    - assets/ingredientes/Queso.jpg
    - assets/ingredientes/Quinoa.jpg
    - assets/ingredientes/Repollo.jpg
    - assets/ingredientes/Salmon.jpg
    - assets/ingredientes/Tamarindo.jpg
    - assets/ingredientes/Tocino.jpg
    - assets/ingredientes/Tomate_Cherry.jpg
    - assets/ingredientes/tomatillo.jpg
    - assets/ingredientes/Tortilla.jpg
    - assets/ingredientes/Tostadas.jpg
    - assets/ingredientes/Verdolagas.jpg
    - assets/ingredientes/Vinagre_Blanco.jpg
    - assets/ingredientes/Yemas_Huevo.jpg
    - assets/ingredientes/Zanahoria.jpg